site_name: docs/latest

plugins:
  - search

nav:
  - index.md
  - User Guide:
      - entities.md
      - bootstrapping.md
      - production.md
  - Security:
      - authorization.md
  - Contribute:
      - developer-guide.md
