site_name: docs/latest

plugins:
  - search

nav:
    - API:
      - Management: api/management/index.html
      - Catalog: api/catalog/index.html
  - Concepts: concepts.md
  - User Guide:
      - deployment.md
      - bootstrap.md
      - configuration.md
      - storage.md
      - authentication.md
      - authorization.md
      - production.md

  - Contribute:
      - developer-guide.md
      - customize.md
